---
# tasks file for minions
- name: Reset Kubernetes
  shell: "yes | kubeadm reset"
  register: kubeadm_reset

- name: IP address of master
  set_fact:
    master_IPaddress: "{{ hostvars[groups['master'][0]]['ansible_host'] }}"

- name: print IP address of master
  debug:
    msg: "{{ master_IPaddress }}"

- name: Join Kubernetes Cluster
  shell: "kubeadm join --ignore-preflight-errors=all --token {{ token }} --discovery-token-unsafe-skip-ca-verification {{ master_IPaddress }}:6443"
  when: kubeadm_reset is succeeded

- name: Poke kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke

